


CREATE TABLE jobpostings.Agency(
    -- agency_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    name VARCHAR2(100) NOT NULL, 
    work_location VARCHAR2(100),
    division_work_unit VARCHAR2(150),
    additional_info CLOB, -- used this to store very large text values. Bigger than VARCHAR2
    -- usually it is used for long text: descriptions, requirements, instructions. 

    --- Constraint------
    CONSTRAINT agency_name_PK PRIMARY KEY (name)
); 



CREATE TABLE jobpostings.job_position(

    -- identifier for each job position 
    job_id                          NUMBER   NOT NULL, 

    -- title
    business_title                  VARCHAR2(150) NOT NULL,
    civil_service_title             VARCHAR2(200) NOT NULL,
    title_code_no                   VARCHAR2(20),
    "level"                         VARCHAR2(10),
    title_classification	        VARCHAR2(50),

    -- job info 
    job_category                    VARCHAR2(250),
    full_time_part_time_indicator   VARCHAR2(10),
    career_level                    VARCHAR2(50),
    hours_shift                     VARCHAR2(240),
    preferred_skills                CLOB,
    to_apply                        CLOB,
    job_description                 CLOB,
    minimum_qual_requirements       CLOB,
    residency_requirement           CLOB,
    work_location_1                 VARCHAR2(350),
    
    -- salary info
    salary_range_from               NUMBER(8,2),
    salary_range_to                 NUMBER(8,2),
    salary_frequency                VARCHAR2(10),
    
    ---- CONSTRAINT---
    CONSTRAINT job_postion_PK PRIMARY KEY (job_id), 
    

    -- Check if the salary values are non-negative
    CONSTRAINT jobpos_salary_CHK CHECK ( (salary_range_from IS NULL OR salary_range_from >=0 ) 
    AND (salary_range_to IS NULL OR salary_range_to >=0)
    ),
    -- check that salary_range_to is greater than or equal to salary_range_from
    CONSTRAINT jobpos_salary_bound_CHK CHECK (salary_range_to  >= salary_range_from OR salary_range_to IS NULL OR salary_range_from IS NULL),

    -- check that (full_time_part_time_indicator) has valid values
    CONSTRAINT jobpos_salary_freq_CHK CHECK (
    full_time_part_time_indicator IS NULL OR 
    full_time_part_time_indicator IN ('Full Time','Part Time','FT','PT','F','P')
    
    )
    

); 

-- POST (M:N + relation attribute)

CREATE TABLE jobpostings.post(
    
    agency_name VARCHAR2(100) NOT NULL,

    job_id NUMBER NOT NULL,
    posting_date DATE NOT NULL,
    posting_updated DATE NOT NULL, 
    post_until DATE,
    posting_type VARCHAR2(15) NOT NULL,
    number_of_positions NUMBER(4,0) NOT NULL,
    
    --Constraints
    CONSTRAINT post_PK PRIMARY KEY (agency_name, job_id, posting_type),

    -- FK to agency table
    CONSTRAINT post_agency_FK FOREIGN KEY (agency_name) REFERENCES jobpostings.Agency(name),

    -- FK to job_position table
    CONSTRAINT post_job_FK FOREIGN KEY (job_id) REFERENCES jobpostings.job_position(job_id),

    CONSTRAINT post_num_postions_CHK CHECK (number_of_positions >= 1),

    CONSTRAINT post_dates_CHK CHECK (
        posting_updated >= posting_date AND (post_until IS NULL OR post_until >= posting_date )
    )
    
);








--------------------------------------------------------------------------------

------------------------------------------------------------
-- 1) USER & PRIVILEGES
------------------------------------------------------------
CREATE USER NYC IDENTIFIED BY 123; 

GRANT CONNECT TO NYC; 
GRANT RESOURCE TO NYC; 
GRANT UNLIMITED TABLESPACE TO NYC;

CONNECT NYC/123;

------------------------------------------------------------
-- 2) STAGING TABLE: NYC.Job_NYC_Posting (same as your base)
------------------------------------------------------------
CREATE TABLE NYC.Job_NYC_Posting (
  Job_ID NUMBER(6) NOT NULL,
  Agency_Name VARCHAR2(50) NOT NULL,
  Posting_Type VARCHAR2(8) NOT NULL,
  Num_Of_Positions NUMBER(3) NOT NULL,
  Business_Title VARCHAR2(250) NOT NULL,
  Civil_Service_Title VARCHAR2(50) NOT NULL,
  Title_Classification VARCHAR2(50) NOT NULL,
  Title_Code_No VARCHAR2(5) NOT NULL,
  "Level" VARCHAR2(3) NOT NULL,
  Job_Category VARCHAR2(250) NOT NULL,
  Full_Time_Part_Time_indicator CHAR(1) DEFAULT 'F' NOT NULL,
  Career_Level VARCHAR2(50) NOT NULL,
  Salary_Range_From NUMBER(10,2),
  Salary_Range_To NUMBER(10,2),
  Salary_Frequency VARCHAR2(6) NOT NULL,
  Work_Location VARCHAR2(150) NOT NULL,
  Division_Work_Unit VARCHAR2(150) NOT NULL,
  Job_Description CLOB,
  Minimum_Qual_Requirement CLOB,
  Preferred_Skill CLOB,
  Additional_Information VARCHAR2(2200),
  To_Apply VARCHAR2(3000),
  Hour_Shift VARCHAR2(300),
  Work_Location_1 VARCHAR2(400),
  Residency_Requirement CLOB,
  Posting_Date DATE NOT NULL,
  Post_Until DATE,
  Posting_Updated DATE NOT NULL
);

------------------------------------------------------------
-- 3) CORE TABLE: NYC.Job_Position
--    Base: your NYC version
--    Added: salary and FT/PT constraints from jobpostings
------------------------------------------------------------
CREATE TABLE NYC.Job_Position (
    Job_ID NUMBER(6),
    To_Apply VARCHAR2(3000),
    Preferred_Skill CLOB,
    Career_Level VARCHAR2(50) NOT NULL,
    Hour_Shift VARCHAR2(300),
    Job_Description CLOB,
    Minimum_Qual_Requirement CLOB,
    Residency_Requirement CLOB,

    -- keep same name, but use constraint logic from 2nd code
    Full_Time_Part_Time_indicator CHAR(1) DEFAULT 'F' NOT NULL,

    Work_Location_1 VARCHAR2(400),
    Job_Category VARCHAR2(250) NOT NULL,
    Business_Title VARCHAR2(250) NOT NULL,
    Civil_Service_Title VARCHAR2(50) NOT NULL,
    Title_Classification VARCHAR2(50) NOT NULL,
    Title_Code_No VARCHAR2(5) NOT NULL,
    "Level" VARCHAR2(3) NOT NULL,
    Salary_Range_From NUMBER(10,2),
    Salary_Range_To NUMBER(10,2),
    Salary_Frequency VARCHAR2(6) NOT NULL,
    
    CONSTRAINT job_postion_PK PRIMARY KEY (Job_ID),

    -- from jobpos_salary_CHK (adapted to your column names)
    CONSTRAINT jobpos_salary_CHK CHECK (
        (Salary_Range_From IS NULL OR Salary_Range_From >= 0) AND
        (Salary_Range_To   IS NULL OR Salary_Range_To   >= 0)
    ),

    -- from jobpos_salary_bound_CHK
    CONSTRAINT jobpos_salary_bound_CHK CHECK (
        Salary_Range_To >= Salary_Range_From
        OR Salary_Range_To   IS NULL
        OR Salary_Range_From IS NULL
    ),

    -- from jobpos_salary_freq_CHK (on Full_Time_Part_Time_indicator)
    -- (note: column is still CHAR(1); realistically this supports 'F'/'P' best)
    CONSTRAINT jobpos_ftpt_CHK CHECK (
        Full_Time_Part_Time_indicator IS NULL OR
        Full_Time_Part_Time_indicator IN ('F','P','T')  -- you can adjust allowed codes as you like
    )
);

------------------------------------------------------------
-- 4) POPULATE Job_Position FROM staging table
------------------------------------------------------------
INSERT INTO NYC.Job_Position (
  Job_ID,
  To_Apply,
  Preferred_Skill,
  Career_Level,
  Hour_Shift,
  Job_Description,
  Minimum_Qual_Requirement,
  Residency_Requirement,
  Full_Time_Part_Time_indicator,
  Work_Location_1,
  Job_Category,
  Business_Title,
  Civil_Service_Title,
  Title_Classification,
  Title_Code_No,
  "Level",
  Salary_Range_From,
  Salary_Range_To,
  Salary_Frequency
)
SELECT 
  j.Job_ID,
  j.To_Apply,
  j.Preferred_Skill,
  j.Career_Level,
  j.Hour_Shift,
  j.Job_Description,
  j.Minimum_Qual_Requirement,
  j.Residency_Requirement,
  j.Full_Time_Part_Time_indicator,
  j.Work_Location_1,
  j.Job_Category,
  j.Business_Title,
  j.Civil_Service_Title,
  j.Title_Classification,
  j.Title_Code_No,
  j."Level",
  j.Salary_Range_From,
  j.Salary_Range_To,
  j.Salary_Frequency
FROM (
  SELECT 
    Job_ID,
    To_Apply,
    Preferred_Skill,
    Career_Level,
    Hour_Shift,
    Job_Description,
    Minimum_Qual_Requirement,
    Residency_Requirement,
    Full_Time_Part_Time_indicator,
    Work_Location_1,
    Job_Category,
    Business_Title,
    Civil_Service_Title,
    Title_Classification,
    Title_Code_No,
    "Level",
    Salary_Range_From,
    Salary_Range_To,
    Salary_Frequency,
    ROW_NUMBER() OVER (PARTITION BY Job_ID 
                       ORDER BY CASE WHEN Posting_Type = 'EXTERNAL' THEN 1 ELSE 2 END) AS rn
  FROM NYC.Job_NYC_Posting
) j
WHERE j.rn = 1;

------------------------------------------------------------
-- 5) CORE TABLE: NYC.Agency
--    Base: your NYC version, same names
--    (no extra constraints in 2nd code except PK, already here)
------------------------------------------------------------
CREATE TABLE NYC.Agency(
    Agency_Name VARCHAR2(50),
    Division_Work_Unit VARCHAR2(150) NOT NULL,
    Work_Location VARCHAR2(150) NOT NULL,
    Additional_Information VARCHAR2(2200),
    
    CONSTRAINT agencey_PK PRIMARY KEY (Agency_Name)
);
    
INSERT INTO NYC.Agency (
    Agency_Name,
    Division_Work_Unit,
    Work_Location,
    Additional_Information
)
SELECT Agency_Name,
       MIN(Division_Work_Unit),
       MIN(Work_Location),
       MIN(Additional_Information)
FROM NYC.Job_NYC_Posting
GROUP BY Agency_Name;

------------------------------------------------------------
-- 6) CORE TABLE: NYC.Post
--    Base: your NYC version (names/lengths kept)
--    Added: constraints from jobpostings.post
------------------------------------------------------------
CREATE TABLE NYC.Post (
    j_id NUMBER(6),
    a_name VARCHAR2(50),
    Posting_Type VARCHAR2(8),
    Posting_Date DATE NOT NULL,
    Post_Until DATE,
    Posting_Updated DATE NOT NULL,
    Num_Of_Positions NUMBER(3) NOT NULL,
    
    CONSTRAINT post_PK PRIMARY KEY (j_id, a_name, Posting_Type),
    
    CONSTRAINT post_j_id_FK FOREIGN KEY (j_id)
        REFERENCES NYC.Job_Position(Job_ID),
    
    CONSTRAINT post_a_name_FK FOREIGN KEY (a_name)
        REFERENCES NYC.Agency(Agency_Name),

    -- from post_num_postions_CHK
    CONSTRAINT post_num_positions_CHK CHECK (
        Num_Of_Positions >= 1
    ),

    -- from post_dates_CHK (adapted to your column names)
    CONSTRAINT post_dates_CHK CHECK (
        Posting_Updated >= Posting_Date
        AND (Post_Until IS NULL OR Post_Until >= Posting_Date)
    )
);

INSERT INTO NYC.Post (
    j_id,
    a_name,
    Posting_Type,
    Posting_Date,
    Post_Until,
    Posting_Updated,
    Num_Of_Positions
)
SELECT DISTINCT
    Job_ID,
    Agency_Name,
    Posting_Type,
    Posting_Date,
    Post_Until,
    Posting_Updated,
    Num_Of_Positions
FROM NYC.Job_NYC_Posting;
